"""
Robert Matthews
CS 1400
Section 002
Exercise 3

3.2
Chapter 3, Discussion #4, pg. 78. Show the output for the 4 code fragments given in this question.
"""

"""
From the book:
'show the output that would be generated by each of the following program fragments:'
"""

def main():

    # a
    for i in range(1,11):
        print(i*i)
    print()

    # b
    for i in [1,3,5,7,9]:
        print(i, ":", i**3)
    print(i)
    print()

    # c
    x = 2
    y = 10
    for j in range (0, y, x):
        print(j, end="")
        print(x + y)
    print("done")
    print()

    # d
    ans = 0
    for i in range (1, 11):
        ans = ans + i*i
        print(i)
    print(ans)
    print()
    print("end")

main()

# I added in a blank line in between each section for readability when it runs
